### ISSUE TITLE
Create Dockerfile for building a container image

### ISSUE THREAD

**Issue by ps-89** [game1n/t8-cms#1]

**Comment by ryuusama09** [comment]
I would like to help  @ps-89 , but as I am a beginner I dont know what exactly to do . can you give more proper directions and instructions

**Comment by ps-89** [comment]
@ryuusama09 You can refer to https://dev.to/karanpratapsingh/dockerize-your-react-app-4j2e

We need to do something similar. Creating a Dockerfile for the project. Our project is react-based, and we need to expose port 3000 in the container.

**Comment by ryuusama09** [comment]
> @ryuusama09 Welcome to the project :)
> 
> You can refer to https://dev.to/karanpratapsingh/dockerize-your-react-app-4j2e
> 
> We need to do something similar. Creating a Dockerfile for the project. Our project is react-based, and we need to expose port 3000 in the container. If you have further questions, feel free to ask in this same thread.

yes , according to this creating a dockerfile is not an issue but what all to write in it , can you guide me ?

**Comment by ps-89** [comment]
@ryuusama09 

The first Dockerfile example given in the article is good enough for our project too.

```
FROM node:14-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install
# Copy app files
COPY . .
# Expose port
EXPOSE 3000
# Start the app
CMD [ "yarn", "start" ]
```

This is in a more readable way, what the first example in the article does i.e
```
Use the base node alpine image
set the working directory in the container
copy current code in the working directory
copy yarn.lock and package.json to the working directory
yarn install
expose 3000 port
run the yarn start command
```

If you can make this more efficient, that'd be great too. You can add steps in the readme too, for running the project via Docker.

**Comment by imabhinavagarwal** [comment]
@ps-89 If the issue is still up for grabs, I would like to take it on. I have prior exp with Docker so that should come in handy

**Comment by ps-89** [comment]
Assigned it to you @imabhinavagarwal.
