### ISSUE TITLE
Create reusable Loader using material ui component

### ISSUE THREAD

**Issue by kishankr7979** [game1n/t8-cms#15]
try to make as configurable as possible, all properties should be exposed.

**Comment by ps-89** [comment]
@eLeontev Do you want to take this up?

**Comment by eLeontev** [comment]
yep, I can take care and will preapre a draft for it, but honestly it would be nice to see which props are you going to reuse in that component. Usually if dev want to wrap smt from scratch they need to know usages or start with MVP and extend it based on the new requirements.

I hope we can discuss it during review
